/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as StudentRouteImport } from './routes/_student'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminStaffsRouteImport } from './routes/_admin/staffs'
import { Route as ApproverApprovalsRouteImport } from './routes/_approver/approvals'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as RegistrarOperationsRouteImport } from './routes/_registrar/operations'
import { Route as StudentCredentialsRouteImport } from './routes/_student/credentials'
import { Route as AuthResetPasswordConfirmRouteImport } from './routes/_auth/reset-password.confirm'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffsRoute = AdminStaffsRouteImport.update({
  id: '/staffs',
  path: '/staffs',
  getParentRoute: () => AdminRoute,
} as any)
const ApproverApprovalsRoute = ApproverApprovalsRouteImport.update({
  id: '/_approver/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const RegistrarOperationsRoute = RegistrarOperationsRouteImport.update({
  id: '/_registrar/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCredentialsRoute = StudentCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => StudentRoute,
} as any)
const AuthResetPasswordConfirmRoute =
  AuthResetPasswordConfirmRouteImport.update({
    id: '/confirm',
    path: '/confirm',
    getParentRoute: () => AuthResetPasswordRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/staffs': typeof AdminStaffsRoute
  '/approvals': typeof ApproverApprovalsRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRouteWithChildren
  '/operations': typeof RegistrarOperationsRoute
  '/credentials': typeof StudentCredentialsRoute
  '/reset-password/confirm': typeof AuthResetPasswordConfirmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/staffs': typeof AdminStaffsRoute
  '/approvals': typeof ApproverApprovalsRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRouteWithChildren
  '/operations': typeof RegistrarOperationsRoute
  '/credentials': typeof StudentCredentialsRoute
  '/reset-password/confirm': typeof AuthResetPasswordConfirmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_student': typeof StudentRouteWithChildren
  '/account': typeof AccountRoute
  '/_admin/staffs': typeof AdminStaffsRoute
  '/_approver/approvals': typeof ApproverApprovalsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRouteWithChildren
  '/_registrar/operations': typeof RegistrarOperationsRoute
  '/_student/credentials': typeof StudentCredentialsRoute
  '/_auth/reset-password/confirm': typeof AuthResetPasswordConfirmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/staffs'
    | '/approvals'
    | '/login'
    | '/reset-password'
    | '/operations'
    | '/credentials'
    | '/reset-password/confirm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/staffs'
    | '/approvals'
    | '/login'
    | '/reset-password'
    | '/operations'
    | '/credentials'
    | '/reset-password/confirm'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_auth'
    | '/_student'
    | '/account'
    | '/_admin/staffs'
    | '/_approver/approvals'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_registrar/operations'
    | '/_student/credentials'
    | '/_auth/reset-password/confirm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  AccountRoute: typeof AccountRoute
  ApproverApprovalsRoute: typeof ApproverApprovalsRoute
  RegistrarOperationsRoute: typeof RegistrarOperationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/staffs': {
      id: '/_admin/staffs'
      path: '/staffs'
      fullPath: '/staffs'
      preLoaderRoute: typeof AdminStaffsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_approver/approvals': {
      id: '/_approver/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApproverApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_registrar/operations': {
      id: '/_registrar/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof RegistrarOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student/credentials': {
      id: '/_student/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof StudentCredentialsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_auth/reset-password/confirm': {
      id: '/_auth/reset-password/confirm'
      path: '/confirm'
      fullPath: '/reset-password/confirm'
      preLoaderRoute: typeof AuthResetPasswordConfirmRouteImport
      parentRoute: typeof AuthResetPasswordRoute
    }
  }
}

interface AdminRouteChildren {
  AdminStaffsRoute: typeof AdminStaffsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminStaffsRoute: AdminStaffsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthResetPasswordRouteChildren {
  AuthResetPasswordConfirmRoute: typeof AuthResetPasswordConfirmRoute
}

const AuthResetPasswordRouteChildren: AuthResetPasswordRouteChildren = {
  AuthResetPasswordConfirmRoute: AuthResetPasswordConfirmRoute,
}

const AuthResetPasswordRouteWithChildren =
  AuthResetPasswordRoute._addFileChildren(AuthResetPasswordRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface StudentRouteChildren {
  StudentCredentialsRoute: typeof StudentCredentialsRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCredentialsRoute: StudentCredentialsRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  AccountRoute: AccountRoute,
  ApproverApprovalsRoute: ApproverApprovalsRoute,
  RegistrarOperationsRoute: RegistrarOperationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
