/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminStaffsRouteImport } from './routes/_admin/staffs'
import { Route as ApproverApprovalsRouteImport } from './routes/_approver/approvals'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as RegistrarOperationsRouteImport } from './routes/_registrar/operations'
import { Route as MyCredentialsRouteImport } from './routes/my/credentials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffsRoute = AdminStaffsRouteImport.update({
  id: '/staffs',
  path: '/staffs',
  getParentRoute: () => AdminRoute,
} as any)
const ApproverApprovalsRoute = ApproverApprovalsRouteImport.update({
  id: '/_approver/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const RegistrarOperationsRoute = RegistrarOperationsRouteImport.update({
  id: '/_registrar/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCredentialsRoute = MyCredentialsRouteImport.update({
  id: '/my/credentials',
  path: '/my/credentials',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/staffs': typeof AdminStaffsRoute
  '/approvals': typeof ApproverApprovalsRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/operations': typeof RegistrarOperationsRoute
  '/my/credentials': typeof MyCredentialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/staffs': typeof AdminStaffsRoute
  '/approvals': typeof ApproverApprovalsRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/operations': typeof RegistrarOperationsRoute
  '/my/credentials': typeof MyCredentialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_admin/staffs': typeof AdminStaffsRoute
  '/_approver/approvals': typeof ApproverApprovalsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_registrar/operations': typeof RegistrarOperationsRoute
  '/my/credentials': typeof MyCredentialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/staffs'
    | '/approvals'
    | '/login'
    | '/reset-password'
    | '/operations'
    | '/my/credentials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/staffs'
    | '/approvals'
    | '/login'
    | '/reset-password'
    | '/operations'
    | '/my/credentials'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_auth'
    | '/_admin/staffs'
    | '/_approver/approvals'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_registrar/operations'
    | '/my/credentials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApproverApprovalsRoute: typeof ApproverApprovalsRoute
  RegistrarOperationsRoute: typeof RegistrarOperationsRoute
  MyCredentialsRoute: typeof MyCredentialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/staffs': {
      id: '/_admin/staffs'
      path: '/staffs'
      fullPath: '/staffs'
      preLoaderRoute: typeof AdminStaffsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_approver/approvals': {
      id: '/_approver/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApproverApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_registrar/operations': {
      id: '/_registrar/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof RegistrarOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/credentials': {
      id: '/my/credentials'
      path: '/my/credentials'
      fullPath: '/my/credentials'
      preLoaderRoute: typeof MyCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminStaffsRoute: typeof AdminStaffsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminStaffsRoute: AdminStaffsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApproverApprovalsRoute: ApproverApprovalsRoute,
  RegistrarOperationsRoute: RegistrarOperationsRoute,
  MyCredentialsRoute: MyCredentialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
