/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as StaffApprovalsRouteImport } from './routes/staff/approvals'
import { Route as StaffOperationsRouteImport } from './routes/staff/operations'
import { Route as StaffUsersRouteImport } from './routes/staff/users'
import { Route as StudentCredentialsRouteImport } from './routes/student/credentials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const StaffApprovalsRoute = StaffApprovalsRouteImport.update({
  id: '/staff/approvals',
  path: '/staff/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffOperationsRoute = StaffOperationsRouteImport.update({
  id: '/staff/operations',
  path: '/staff/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffUsersRoute = StaffUsersRouteImport.update({
  id: '/staff/users',
  path: '/staff/users',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCredentialsRoute = StudentCredentialsRouteImport.update({
  id: '/student/credentials',
  path: '/student/credentials',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/staff/approvals': typeof StaffApprovalsRoute
  '/staff/operations': typeof StaffOperationsRoute
  '/staff/users': typeof StaffUsersRoute
  '/student/credentials': typeof StudentCredentialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/staff/approvals': typeof StaffApprovalsRoute
  '/staff/operations': typeof StaffOperationsRoute
  '/staff/users': typeof StaffUsersRoute
  '/student/credentials': typeof StudentCredentialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/staff/approvals': typeof StaffApprovalsRoute
  '/staff/operations': typeof StaffOperationsRoute
  '/staff/users': typeof StaffUsersRoute
  '/student/credentials': typeof StudentCredentialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/staff/approvals'
    | '/staff/operations'
    | '/staff/users'
    | '/student/credentials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/staff/approvals'
    | '/staff/operations'
    | '/staff/users'
    | '/student/credentials'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/staff/approvals'
    | '/staff/operations'
    | '/staff/users'
    | '/student/credentials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  StaffApprovalsRoute: typeof StaffApprovalsRoute
  StaffOperationsRoute: typeof StaffOperationsRoute
  StaffUsersRoute: typeof StaffUsersRoute
  StudentCredentialsRoute: typeof StudentCredentialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/staff/approvals': {
      id: '/staff/approvals'
      path: '/staff/approvals'
      fullPath: '/staff/approvals'
      preLoaderRoute: typeof StaffApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/operations': {
      id: '/staff/operations'
      path: '/staff/operations'
      fullPath: '/staff/operations'
      preLoaderRoute: typeof StaffOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/users': {
      id: '/staff/users'
      path: '/staff/users'
      fullPath: '/staff/users'
      preLoaderRoute: typeof StaffUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/credentials': {
      id: '/student/credentials'
      path: '/student/credentials'
      fullPath: '/student/credentials'
      preLoaderRoute: typeof StudentCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  StaffApprovalsRoute: StaffApprovalsRoute,
  StaffOperationsRoute: StaffOperationsRoute,
  StaffUsersRoute: StaffUsersRoute,
  StudentCredentialsRoute: StudentCredentialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
