name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore backend dependencies
        run: dotnet restore

      - name: Build backend
        run: dotnet build --no-restore --configuration Release

      - name: Test backend
        run: dotnet test --no-build --configuration Release

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install frontend dependencies
        working-directory: ./src/UniDipVeri.Web
        run: bun install --frozen-lockfile

      - name: Lint frontend
        working-directory: ./src/UniDipVeri.Web
        run: bun run lint

      - name: Build frontend
        working-directory: ./src/UniDipVeri.Web
        run: bun run build
